model_list:
  - model_name: external-llm
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME
      aws_session_token: os.environ/AWS_SESSION_TOKEN

litellm_settings:
  modify_params: true
  drop_params: true
